version: "3.8"

services:
  cms-db:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_DATABASE: cms
      MYSQL_USER: cms
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - xibo_db:/var/lib/mysql
    mem_limit: 1g

  cms-xmr:
    image: ghcr.io/xibosignage/xibo-xmr:1.0
    restart: always
    ports:
      - "9505:9505"
    mem_limit: 256m

  cms-memcached:
    image: memcached:alpine
    restart: always
    command: memcached -m 15
    mem_limit: 100m

  cms-quickchart:
    image: ianw/quickchart
    restart: always

  cms-web:
    image: ghcr.io/xibosignage/xibo-cms:release-4.4.0
    restart: always
    depends_on:
      - cms-db
      - cms-xmr
      - cms-memcached
      - cms-quickchart
    environment:
      MYSQL_HOST: cms-db
      MYSQL_DATABASE: cms
      MYSQL_USER: cms
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      XMR_HOST: cms-xmr
      CMS_USE_MEMCACHED: "true"
      MEMCACHED_HOST: cms-memcached
    ports:
      - "85:80"
    volumes:
      - xibo_custom:/var/www/cms/custom
      - xibo_backup:/var/www/backup
      - xibo_theme_custom:/var/www/cms/web/theme/custom
      - xibo_library:/var/www/cms/library
      - xibo_userscripts:/var/www/cms/web/userscripts
      - xibo_cacerts:/var/www/cms/ca-certs
    mem_limit: 1g

volumes:
  xibo_db:
  xibo_custom:
  xibo_backup:
  xibo_theme_custom:
  xibo_library:
  xibo_userscripts:
  xibo_cacerts:
